### ISSUE TITLE
Eliminación de pedidos

### ISSUE THREAD

**Issue by DavidLapi98** [katacliny/practica#24]
Resumen:
Quiero que en la aplicación se puedan eliminar pedidos de la lista de pedidos.
Descripción: 
Estando en la pantalla 'Ver Pedidos y Facturas' quiero tener un botón 'Eliminar'. Si se hace click en un pedido anteriormente creado y, a continuación, pulsamos este botón, el pedido desaparecerá de la lista situada en la parte superior.
En la parte inferior de la pantalla tenemos el botón 'Volver'. Si lo pulsamos, nos devuelve a la pantalla 'Consumidores'.

**Comment by VictorPelGar** [comment]
Resumen:
Quiero que en la aplicación se puedan eliminar consumidores.
Descripción: Estando en la pantalla 'Consumidores' quiero tener un botón 'Eliminar'. Si se hace click en un consumidor anteriormente creado y, a continuación, pulsamos este botón, el consumidor desaparecerá de la lista situada en la parte superior.
