### ISSUE TITLE
Acceso a los consumidores

### ISSUE THREAD

**Issue by VictorPelGar** [katacliny/practica#27]
Resumen:
Quiero que la aplicación me permita acceder a los consumidores como usuario.
Descripción: Estando en la pantalla 'Principal' quiero tener dos input para el usuario y contraseña. Ambos deben estar correctamente para que puedan ser verificados.
Una vez rellenados los campos, debemos hacer click en el check box 'Usuario' y, por último, el botón 'Acceder' que nos llevará a la pantalla 'Consumidores'. Al lado de este botón, tenemos 'Cancelar', que al pulsarlo se borraría el contenido de los campos usuario y contraseña al igual que se quitaría la elección del check box 'Usuario'.

**Comment by DavidLapi98** [comment]
Resumen:
Quiero que la aplicación me permita acceder a los consumidores.
Descripción: Estando en la pantalla 'Principal' quiero tener los siguientes pasos:
1. 2 inputs en el que me pueda loguearme con 'Usuario' y 'Contraseña' almacenados en BBDD.
2. 2 checkbox en las cuales pueda elegir entre 'administrador' y 'consumidor' (en nuestro caso, consumidor)
3. 2 botones: 'Acceder' que me permita, al pulsarlo, acceder a la pantalla 'Consumidores' dónde podría realizar distintas funcionalidades como crear, eliminar o modificar un determinado consumidor, y 'Cancelar' en el que, una vez pulsado, nos elimina los datos introducidos.
Una vez situado en la pantalla 'Consumidores', tenemos un botón 'Volver' en la parte inferior que si lo pulsamos la aplicación volvería a su pantalla inicial (pantalla 'Principal').
